package goldenvec_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/feirai/averin/server/internal/broker"
	"github.com/feirai/averin/server/internal/resourceshim"
)

// These rows are generated by the executable Lean oracle. Compare the actual Go
// producers with SHA-256 of the modeled bytes, including every field mutation.
func TestGoPreimageProducersMatchLeanOracle(t *testing.T) {
	_, self, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(self), "..", "..", "..")
	type field struct {
		S   *string `json:"s"`
		U64 *int64  `json:"u64"`
		Hex *string `json:"hex"`
	}
	type inputRow struct {
		Family string  `json:"family"`
		Fields []field `json:"fields"`
	}
	type outputRow struct {
		Family string `json:"family"`
		Hex    string `json:"hex"`
	}
	var inputs struct {
		Families []inputRow `json:"families"`
		Variants []inputRow `json:"preimage_variants"`
	}
	var expected struct {
		Families []outputRow `json:"families"`
		Variants []outputRow `json:"preimage_variants"`
	}
	read := func(name string, dst any) {
		t.Helper()
		b, err := os.ReadFile(filepath.Join(root, "formal", "oracle", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := json.Unmarshal(b, dst); err != nil {
			t.Fatal(err)
		}
	}
	read("inputs.json", &inputs)
	read("expected.json", &expected)
	var firstGrant broker.GrantSeqHash
	for _, row := range inputs.Families {
		if row.Family == "grant head step" {
			firstGrant = broker.GrantSeqHash{Seq: *row.Fields[1].U64, ContentHash: *row.Fields[2].S}
			break
		}
	}
	if firstGrant.ContentHash == "" {
		t.Fatal("missing first grant-head step")
	}
	check := func(ins []inputRow, outs []outputRow) {
		t.Helper()
		if len(ins) != len(outs) {
			t.Fatalf("oracle rows: %d inputs, %d expected", len(ins), len(outs))
		}
		for n, row := range ins {
			wantRow := outs[n]
			if row.Family != wantRow.Family {
				t.Fatalf("oracle row %d family mismatch", n)
			}
			pre, err := hex.DecodeString(wantRow.Hex)
			if err != nil {
				t.Fatal(err)
			}
			sum := sha256.Sum256(pre)
			str := func(i int) string {
				if row.Fields[i].S == nil {
					t.Fatalf("%s field %d not string", row.Family, i)
				}
				return *row.Fields[i].S
			}
			num := func(i int) int64 {
				if row.Fields[i].U64 == nil {
					t.Fatalf("%s field %d not integer", row.Family, i)
				}
				return *row.Fields[i].U64
			}
			got := ""
			switch row.Family {
			case "use PoP":
				got = hex.EncodeToString(resourceshim.UsePoPChallenge(str(0), str(1), str(2), str(3), str(4), str(5)))
			case "cosig approval":
				got = hex.EncodeToString(broker.CosigApprovalChallenge(str(0), str(1), str(2), num(3), num(4)))
			case "delegation hop":
				got = hex.EncodeToString(broker.DelegationHopChallenge(str(0), num(1), str(2), str(3), str(4), str(5), str(6), num(7)))
			case "introspection transcript":
				got = hex.EncodeToString(broker.IntrospectionTranscriptChallenge(str(0), str(1), str(2), str(3), num(4), num(5)))
			case "federation cert":
				got = hex.EncodeToString(broker.FederationCertChallenge(str(0), str(1), str(2), str(3), str(4), num(5)))
			case "revocation leaf":
				leaf := broker.RevocationLeaf(str(0))
				got = hex.EncodeToString(leaf[:])
			case "grant head seed":
				got = strings.TrimPrefix(broker.GrantHeadRoot(nil), "sha256:")
			case "grant head step":
				if row.Fields[0].Hex == nil {
					t.Fatal("grant head step missing accumulator")
				}
				grants := []broker.GrantSeqHash{}
				switch *row.Fields[0].Hex {
				case strings.TrimPrefix(broker.GrantHeadRoot(nil), "sha256:"):
				case strings.TrimPrefix(broker.GrantHeadRoot([]broker.GrantSeqHash{firstGrant}), "sha256:"):
					grants = append(grants, firstGrant)
				default:
					t.Fatal("grant head step accumulator is not a production prefix")
				}
				grants = append(grants, broker.GrantSeqHash{Seq: num(1), ContentHash: str(2)})
				got = strings.TrimPrefix(broker.GrantHeadRoot(grants), "sha256:")
			default:
				continue // other families are not Go broker/resource producers
			}
			if got != hex.EncodeToString(sum[:]) {
				t.Errorf("%s row %d: Go digest %s != Lean-preimage digest %x", row.Family, n, got, sum)
			}
		}
	}
	check(inputs.Families, expected.Families)
	check(inputs.Variants, expected.Variants)
}
