#!/usr/bin/env python3
"""Generate core/src/kani_string_cases.rs: one Kani harness per string_escape_roundtrip case id.

    python3 formal/gen-kani-string-cases.py          # rewrite the table
    python3 formal/gen-kani-string-cases.py --check  # fail if the committed table differs

check-kani-shards.py runs the same comparison before any string harness is run.
"""

import sys
from pathlib import Path

TABLE = Path(__file__).resolve().parents[1] / "core/src/kani_string_cases.rs"
CASES = 1 + 130 + 130 * 130


def harness_name(k: int) -> str:
    return f"string_escape_roundtrip_{k:05d}"


def render() -> str:
    lines = [
        "// @generated by formal/gen-kani-string-cases.py; do not edit.",
        "// One string_escape_roundtrip harness per case id of `string_proof_case` (canon.rs),",
        f"// ids 0..{CASES}; included into canon.rs's `kani_proofs` module under cfg(kani).",
    ]
    lines += [f"string_case!({harness_name(k)}, {k});" for k in range(CASES)]
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if sys.argv[1:] == ["--check"]:
        if not TABLE.exists() or TABLE.read_text() != text:
            print("gen-kani-string-cases: table is stale; regenerate it", file=sys.stderr)
            return 1
        return 0
    if sys.argv[1:]:
        print(__doc__, file=sys.stderr)
        return 2
    TABLE.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
