-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [averin_decision_core]: function definitions
import Aeneas
import Extracted.Types
import Extracted.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace averin_decision_core

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialEq<[U]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 14:0-16:28
    Name pattern: [core::cmp::PartialEq<[@T], [@U]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T], [@U]>"]
impl_def Slice.Insts.CoreCmpPartialEqSlice {T : Type} {U : Type}
  (cmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (Slice T)
  (Slice U) := {
  eq := core.slice.cmp.PartialEqSlice.eq cmpPartialEqInst
  ne := core.cmp.PartialEq.ne.trait_default (Slice.Insts.CoreCmpPartialEqSlice
    cmpPartialEqInst)
}

/-- [averin_decision_core::canon::member]: loop 0:
    Source: 'core/src/canon.rs', lines 170:4-172:5 -/
@[rust_loop]
def canon.member_loop
  (members : alloc.vec.Vec (String × canon.CanonValue)) (key : Str)
  (i : Std.Usize) :
  Result Std.Usize
  := do
  let i1 := alloc.vec.Vec.len members
  if i < i1
  then
    let (s, _) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
        canon.CanonValue)) members i
    let s1 ← alloc.string.String.as_bytes s
    let s2 ← core.str.Str.as_bytes key
    let b ←
      core.cmp.impls.PartialEqShared.ne (Slice.Insts.CoreCmpPartialEqSlice
        core.cmp.PartialEqU8) s1 s2
    if b
    then let i2 ← i + 1#usize
         canon.member_loop members key i2
    else ok i
  else ok i
partial_fixpoint

/-- [averin_decision_core::canon::member]:
    Source: 'core/src/canon.rs', lines 164:0-178:1 -/
def canon.member
  (v : canon.CanonValue) (key : Str) : Result (Option canon.CanonValue) := do
  match v with
  | canon.CanonValue.Null => ok none
  | canon.CanonValue.Bool _ => ok none
  | canon.CanonValue.Int _ => ok none
  | canon.CanonValue.Str _ => ok none
  | canon.CanonValue.Array _ => ok none
  | canon.CanonValue.Object m =>
    let i ← canon.member_loop m key 0#usize
    let i1 := alloc.vec.Vec.len m
    if i < i1
    then
      let (_, cv) ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
          canon.CanonValue)) m i
      ok (some cv)
    else ok none

/-- [averin_decision_core::canon::hex_digit]:
    Source: 'core/src/canon.rs', lines 476:0-482:1 -/
def canon.hex_digit (n : Std.U8) : Result Std.U8 := do
  if n < 10#u8
  then 48#u8 + n
  else let i ← n - 10#u8
       97#u8 + i

/-- [averin_decision_core::canon::escape_into]: loop 0:
    Source: 'core/src/canon.rs', lines 446:4-464:5 -/
@[rust_loop]
def canon.escape_into_loop
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i1 := Slice.len s
  if i < i1
  then
    let b ← Slice.index_usize s i
    let out1 ←
      match b with
      | 34#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 34#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 92#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 92#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 8#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 98#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 9#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 116#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 10#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 110#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 12#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 102#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | 13#uscalar =>
        do
        let s1 ← lift (Array.to_slice (Array.make 2#usize [ 92#u8, 114#u8 ]))
        alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
      | _ =>
        if 0#u8 <= b
        then
          if b <= 31#u8
          then
            do
            let s1 ←
              lift (Array.to_slice
                (Array.make 4#usize [ 92#u8, 117#u8, 48#u8, 48#u8 ]))
            let out2 ←
              alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s1
            let i2 ← b >>> 4#i32
            let i3 ← canon.hex_digit i2
            let out3 ← alloc.vec.Vec.push out2 i3
            let i4 ← lift (b &&& 15#u8)
            let i5 ← canon.hex_digit i4
            alloc.vec.Vec.push out3 i5
          else alloc.vec.Vec.push out b
        else alloc.vec.Vec.push out b
    let i2 ← i + 1#usize
    canon.escape_into_loop s out1 i2
  else ok out
partial_fixpoint

/-- [averin_decision_core::canon::escape_into]:
    Source: 'core/src/canon.rs', lines 443:0-466:1 -/
def canon.escape_into
  (s : Slice Std.U8) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← alloc.vec.Vec.push out 34#u8
  let out2 ← canon.escape_into_loop s out1 0#usize
  alloc.vec.Vec.push out2 34#u8

/-- [averin_decision_core::canon::write_int]: loop 0:
    Source: 'core/src/canon.rs', lines 424:4-431:5 -/
@[rust_loop]
def canon.write_int_loop
  (u : Std.U64) (digits : Array Std.U8 20#usize) (k : Std.Usize) :
  Result (Std.Usize × (Array Std.U8 20#usize))
  := do
  let k1 ← k - 1#usize
  let i ← u % 10#u64
  let i1 ← lift (UScalar.cast .U8 i)
  let i2 ← 48#u8 + i1
  let (_, index_mut_back) ← Array.index_mut_usize digits k1
  let u1 ← u / 10#u64
  if u1 = 0#u64
  then ok (k1, index_mut_back i2)
  else let a := index_mut_back i2
       canon.write_int_loop u1 a k1
partial_fixpoint

/-- [averin_decision_core::canon::write_int]:
    Source: 'core/src/canon.rs', lines 414:0-433:1 -/
def canon.write_int
  (n : Std.I64) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let (out1, u) ←
    if n < 0#i64
    then
      do
      let out2 ← alloc.vec.Vec.push out 45#u8
      let i ← n + 1#i64
      let i1 ← -. i
      let i2 ← lift (IScalar.hcast .U64 i1)
      let u1 ← i2 + 1#u64
      ok (out2, u1)
    else do
         let u1 ← lift (IScalar.hcast .U64 n)
         ok (out, u1)
  let digits := Array.repeat 20#usize 0#u8
  let (k, back) ← canon.write_int_loop u digits 20#usize
  let s ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) back
      { start := k }
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s

/-- [averin_decision_core::canon::utf16_units]: loop 0:
    Source: 'core/src/canon.rs', lines 369:4-396:5 -/
@[rust_loop]
def canon.utf16_units_loop
  (s : Slice Std.U8) (units : alloc.vec.Vec Std.U16) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U16)
  := do
  let i1 := Slice.len s
  if i < i1
  then
    let i2 ← Slice.index_usize s i
    let b0 ← lift (UScalar.cast .U32 i2)
    let (cp, width) ←
      if b0 < 128#u32
      then ok (b0, 1#usize)
      else
        if b0 < 224#u32
        then
          do
          let i3 ← b0 - 192#u32
          let i4 ← i3 * 64#u32
          let i5 ← i + 1#usize
          let i6 ← Slice.index_usize s i5
          let i7 ← lift (UScalar.cast .U32 i6)
          let i8 ← i7 - 128#u32
          let i9 ← i4 + i8
          ok (i9, 2#usize)
        else
          if b0 < 240#u32
          then
            do
            let i3 ← b0 - 224#u32
            let i4 ← i3 * 4096#u32
            let i5 ← i + 1#usize
            let i6 ← Slice.index_usize s i5
            let i7 ← lift (UScalar.cast .U32 i6)
            let i8 ← i7 - 128#u32
            let i9 ← i8 * 64#u32
            let i10 ← i4 + i9
            let i11 ← i + 2#usize
            let i12 ← Slice.index_usize s i11
            let i13 ← lift (UScalar.cast .U32 i12)
            let i14 ← i13 - 128#u32
            let i15 ← i10 + i14
            ok (i15, 3#usize)
          else
            do
            let i3 ← b0 - 240#u32
            let i4 ← i3 * 262144#u32
            let i5 ← i + 1#usize
            let i6 ← Slice.index_usize s i5
            let i7 ← lift (UScalar.cast .U32 i6)
            let i8 ← i7 - 128#u32
            let i9 ← i8 * 4096#u32
            let i10 ← i4 + i9
            let i11 ← i + 2#usize
            let i12 ← Slice.index_usize s i11
            let i13 ← lift (UScalar.cast .U32 i12)
            let i14 ← i13 - 128#u32
            let i15 ← i14 * 64#u32
            let i16 ← i10 + i15
            let i17 ← i + 3#usize
            let i18 ← Slice.index_usize s i17
            let i19 ← lift (UScalar.cast .U32 i18)
            let i20 ← i19 - 128#u32
            let i21 ← i16 + i20
            ok (i21, 4#usize)
    let units1 ←
      if cp < 65536#u32
      then
        do
        let i3 ← lift (UScalar.cast .U16 cp)
        alloc.vec.Vec.push units i3
      else
        do
        let i3 ← cp - 65536#u32
        let i4 ← i3 / 1024#u32
        let i5 ← 55296#u32 + i4
        let i6 ← lift (UScalar.cast .U16 i5)
        let units2 ← alloc.vec.Vec.push units i6
        let i7 ← i3 % 1024#u32
        let i8 ← 56320#u32 + i7
        let i9 ← lift (UScalar.cast .U16 i8)
        alloc.vec.Vec.push units2 i9
    let i3 ← i + width
    canon.utf16_units_loop s units1 i3
  else ok units
partial_fixpoint

/-- [averin_decision_core::canon::utf16_units]:
    Source: 'core/src/canon.rs', lines 366:0-398:1 -/
def canon.utf16_units (s : Slice Std.U8) : Result (alloc.vec.Vec Std.U16) := do
  let i := Slice.len s
  let units := alloc.vec.Vec.with_capacity Std.U16 i
  canon.utf16_units_loop s units 0#usize

/-- [averin_decision_core::canon::units_lt]: loop 0:
    Source: 'core/src/canon.rs', lines 355:4-357:5 -/
@[rust_loop]
def canon.units_lt_loop
  (a : Slice Std.U16) (b : Slice Std.U16) (n : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  if i < n
  then
    let i1 ← Slice.index_usize a i
    let i2 ← Slice.index_usize b i
    if i1 = i2
    then let i3 ← i + 1#usize
         canon.units_lt_loop a b n i3
    else ok i
  else ok i
partial_fixpoint

/-- [averin_decision_core::canon::units_lt]:
    Source: 'core/src/canon.rs', lines 352:0-363:1 -/
def canon.units_lt (a : Slice Std.U16) (b : Slice Std.U16) : Result Bool := do
  let i := Slice.len a
  let i1 := Slice.len b
  let n ← if i < i1
            then ok (Slice.len a)
            else ok (Slice.len b)
  let i2 ← canon.units_lt_loop a b n 0#usize
  if i2 < n
  then
    let i3 ← Slice.index_usize a i2
    let i4 ← Slice.index_usize b i2
    ok (i3 < i4)
  else let i3 := Slice.len a
       let i4 := Slice.len b
       ok (i3 < i4)

/-- [averin_decision_core::canon::merge_by_units]: loop 0:
    Source: 'core/src/canon.rs', lines 339:4-347:5 -/
@[rust_loop]
def canon.merge_by_units_loop
  (units : Slice (alloc.vec.Vec Std.U16)) (left : Slice Std.Usize)
  (right : Slice Std.Usize) (out : alloc.vec.Vec Std.Usize) (i : Std.Usize)
  (j : Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  let i1 := Slice.len left
  if i < i1
  then
    let i2 := Slice.len right
    if j = i2
    then
      let i3 ← Slice.index_usize left i
      let out1 ← alloc.vec.Vec.push out i3
      let i4 ← i + 1#usize
      canon.merge_by_units_loop units left right out1 i4 j
    else
      let i3 := Slice.len left
      if i < i3
      then
        let i4 ← Slice.index_usize right j
        let v ← Slice.index_usize units i4
        let s := alloc.vec.Vec.deref v
        let i5 ← Slice.index_usize left i
        let v1 ← Slice.index_usize units i5
        let s1 := alloc.vec.Vec.deref v1
        let b ← canon.units_lt s s1
        if b
        then
          let out1 ← alloc.vec.Vec.push out i4
          let j1 ← j + 1#usize
          canon.merge_by_units_loop units left right out1 i j1
        else
          let out1 ← alloc.vec.Vec.push out i5
          let i6 ← i + 1#usize
          canon.merge_by_units_loop units left right out1 i6 j
      else
        let i4 ← Slice.index_usize right j
        let out1 ← alloc.vec.Vec.push out i4
        let j1 ← j + 1#usize
        canon.merge_by_units_loop units left right out1 i j1
  else
    let i2 := Slice.len right
    if j < i2
    then
      let i3 := Slice.len right
      if j = i3
      then
        let i4 ← Slice.index_usize left i
        let out1 ← alloc.vec.Vec.push out i4
        let i5 ← i + 1#usize
        canon.merge_by_units_loop units left right out1 i5 j
      else
        let i4 := Slice.len left
        if i < i4
        then
          let i5 ← Slice.index_usize right j
          let v ← Slice.index_usize units i5
          let s := alloc.vec.Vec.deref v
          let i6 ← Slice.index_usize left i
          let v1 ← Slice.index_usize units i6
          let s1 := alloc.vec.Vec.deref v1
          let b ← canon.units_lt s s1
          if b
          then
            let out1 ← alloc.vec.Vec.push out i5
            let j1 ← j + 1#usize
            canon.merge_by_units_loop units left right out1 i j1
          else
            let out1 ← alloc.vec.Vec.push out i6
            let i7 ← i + 1#usize
            canon.merge_by_units_loop units left right out1 i7 j
        else
          let i5 ← Slice.index_usize right j
          let out1 ← alloc.vec.Vec.push out i5
          let j1 ← j + 1#usize
          canon.merge_by_units_loop units left right out1 i j1
    else ok out
partial_fixpoint

/-- [averin_decision_core::canon::merge_by_units]:
    Source: 'core/src/canon.rs', lines 335:0-349:1 -/
def canon.merge_by_units
  (units : Slice (alloc.vec.Vec Std.U16)) (left : Slice Std.Usize)
  (right : Slice Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  let i := Slice.len left
  let i1 := Slice.len right
  let i2 ← i + i1
  let out := alloc.vec.Vec.with_capacity Std.Usize i2
  canon.merge_by_units_loop units left right out 0#usize 0#usize

/-- [averin_decision_core::canon::sort_by_units]:
    Source: 'core/src/canon.rs', lines 324:0-333:1 -/
def canon.sort_by_units
  (units : Slice (alloc.vec.Vec Std.U16)) (pos : Slice Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  let i := Slice.len pos
  if i <= 1#usize
  then alloc.slice.Slice.to_vec core.clone.CloneUsize pos
  else
    let i1 := Slice.len pos
    let i2 := Slice.len pos
    let i3 ← i2 / 2#usize
    let mid ← i1 - i3
    let s ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeToUsizeSlice Std.Usize) pos
        { «end» := mid }
    let left ← canon.sort_by_units units s
    let s1 ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeFromUsizeSlice Std.Usize) pos
        { start := mid }
    let right ← canon.sort_by_units units s1
    let s2 := alloc.vec.Vec.deref left
    let s3 := alloc.vec.Vec.deref right
    canon.merge_by_units units s2 s3
partial_fixpoint

/-- [averin_decision_core::canon::positions]: loop 0:
    Source: 'core/src/canon.rs', lines 315:4-318:5 -/
@[rust_loop]
def canon.positions_loop
  (n : Std.Usize) (pos : alloc.vec.Vec Std.Usize) (p : Std.Usize) :
  Result (alloc.vec.Vec Std.Usize)
  := do
  if p < n
  then
    let pos1 ← alloc.vec.Vec.push pos p
    let p1 ← p + 1#usize
    canon.positions_loop n pos1 p1
  else ok pos
partial_fixpoint

/-- [averin_decision_core::canon::positions]:
    Source: 'core/src/canon.rs', lines 312:0-320:1 -/
def canon.positions (n : Std.Usize) : Result (alloc.vec.Vec Std.Usize) := do
  let pos := alloc.vec.Vec.with_capacity Std.Usize n
  canon.positions_loop n pos 0#usize

/-- [averin_decision_core::canon::unmark_key]: loop 0:
    Source: 'core/src/canon.rs', lines 264:4-269:5 -/
@[rust_loop]
def canon.unmark_key_loop
  (members : alloc.vec.Vec (String × canon.CanonValue)) (key : Slice Std.U8)
  (keep : Slice Bool) (j : Std.Usize) :
  Result (Slice Bool)
  := do
  let i := alloc.vec.Vec.len members
  if j < i
  then
    let (s, _) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
        canon.CanonValue)) members j
    let s1 ← alloc.string.String.as_bytes s
    let b ← core.slice.cmp.PartialEqSlice.eq core.cmp.PartialEqU8 s1 key
    let keep1 ← if b
                  then Slice.update keep j false
                  else ok keep
    let j1 ← j + 1#usize
    canon.unmark_key_loop members key keep1 j1
  else ok keep
partial_fixpoint

/-- [averin_decision_core::canon::unmark_key]:
    Source: 'core/src/canon.rs', lines 262:0-270:1 -/
@[reducible]
def canon.unmark_key
  (members : alloc.vec.Vec (String × canon.CanonValue)) (key : Slice Std.U8)
  (keep : Slice Bool) :
  Result (Slice Bool)
  := do
  canon.unmark_key_loop members key keep 0#usize

/-- [averin_decision_core::canon::unmark_stripped]:
    Source: 'core/src/canon.rs', lines 247:0-257:1 -/
def canon.unmark_stripped
  (members : alloc.vec.Vec (String × canon.CanonValue)) (strip : Slice Str)
  (i : Std.Usize) (keep : Slice Bool) :
  Result (Slice Bool)
  := do
  let i1 := Slice.len strip
  if i < i1
  then
    let s ← Slice.index_usize strip i
    let s1 ← core.str.Str.as_bytes s
    let keep1 ← canon.unmark_key members s1 keep
    let i2 ← i + 1#usize
    canon.unmark_stripped members strip i2 keep1
  else ok keep
partial_fixpoint

/-- [averin_decision_core::canon::write_members]: loop 0:
    Source: 'core/src/canon.rs', lines 279:4-287:5 -/
@[rust_loop]
def canon.write_members_loop0
  (members : alloc.vec.Vec (String × canon.CanonValue)) (keep : Slice Bool)
  (keys : alloc.vec.Vec String) (units : alloc.vec.Vec (alloc.vec.Vec Std.U16))
  (src : alloc.vec.Vec Std.Usize) (i : Std.Usize) :
  Result ((alloc.vec.Vec String) × (alloc.vec.Vec (alloc.vec.Vec Std.U16)) ×
    (alloc.vec.Vec Std.Usize))
  := do
  let i1 := alloc.vec.Vec.len members
  if i < i1
  then
    let b ← Slice.index_usize keep i
    let (keys1, units1, src1) ←
      if b
      then
        do
        let (s, _) ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
            canon.CanonValue)) members i
        let s1 ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref s
        let key ← canon.nfc s1
        let s2 ← alloc.string.String.as_bytes key
        let v ← canon.utf16_units s2
        let units2 ← alloc.vec.Vec.push units v
        let keys2 ← alloc.vec.Vec.push keys key
        let src2 ← alloc.vec.Vec.push src i
        ok (keys2, units2, src2)
      else ok (keys, units, src)
    let i2 ← i + 1#usize
    canon.write_members_loop0 members keep keys1 units1 src1 i2
  else ok (keys, units, src)
partial_fixpoint

mutual

/-- [averin_decision_core::canon::write_canonical]:
    Source: 'core/src/canon.rs', lines 183:0-208:1 -/
def canon.write_canonical
  (v : canon.CanonValue) (out : alloc.vec.Vec Std.U8) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  match v with
  | canon.CanonValue.Null =>
    let s ←
      lift (Array.to_slice
        (Array.make 4#usize [ 110#u8, 117#u8, 108#u8, 108#u8 ]))
    let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
    ok (true, out1)
  | canon.CanonValue.Bool b =>
    if b
    then
      let s ←
        lift (Array.to_slice
          (Array.make 4#usize [ 116#u8, 114#u8, 117#u8, 101#u8 ]))
      let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
      ok (true, out1)
    else
      let s ←
        lift (Array.to_slice
          (Array.make 5#usize [ 102#u8, 97#u8, 108#u8, 115#u8, 101#u8 ]))
      let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
      ok (true, out1)
  | canon.CanonValue.Int n =>
    let out1 ← canon.write_int n out
    ok (true, out1)
  | canon.CanonValue.Str s =>
    let s1 ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref s
    let s2 ← canon.nfc s1
    let s3 ← alloc.string.String.as_bytes s2
    let out1 ← canon.escape_into s3 out
    ok (true, out1)
  | canon.CanonValue.Array items =>
    let s := alloc.vec.Vec.deref items
    canon.write_array s out
  | canon.CanonValue.Object members =>
    let s ← lift (Array.to_slice (Std.Array.empty Str))
    canon.write_object members s out
partial_fixpoint

/-- [averin_decision_core::canon::write_array]: loop 0:
    Source: 'core/src/canon.rs', lines 214:4-222:5 -/
@[rust_loop]
def canon.write_array_loop
  (items : Slice canon.CanonValue) (out : alloc.vec.Vec Std.U8) (unique : Bool)
  (i : Std.Usize) :
  Result ((alloc.vec.Vec Std.U8) × Bool)
  := do
  let i1 := Slice.len items
  if i < i1
  then
    let out1 ← if i > 0#usize
                 then alloc.vec.Vec.push out 44#u8
                 else ok out
    let cv ← Slice.index_usize items i
    let (b, out2) ← canon.write_canonical cv out1
    let unique1 ← if b
                    then ok unique
                    else ok false
    let i2 ← i + 1#usize
    canon.write_array_loop items out2 unique1 i2
  else ok (out, unique)
partial_fixpoint

/-- [averin_decision_core::canon::write_array]:
    Source: 'core/src/canon.rs', lines 210:0-225:1 -/
def canon.write_array
  (items : Slice canon.CanonValue) (out : alloc.vec.Vec Std.U8) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  let out1 ← alloc.vec.Vec.push out 91#u8
  let (out2, unique) ← canon.write_array_loop items out1 true 0#usize
  let out3 ← alloc.vec.Vec.push out2 93#u8
  ok (unique, out3)
partial_fixpoint

/-- [averin_decision_core::canon::write_object]:
    Source: 'core/src/canon.rs', lines 234:0-242:1 -/
def canon.write_object
  (members : alloc.vec.Vec (String × canon.CanonValue)) (strip : Slice Str)
  (out : alloc.vec.Vec Std.U8) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  let i := alloc.vec.Vec.len members
  let keep ← alloc.vec.from_elem core.clone.CloneBool true i
  let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut keep)
  let s1 ← canon.unmark_stripped members strip 0#usize s
  let keep1 := deref_mut_back s1
  let s2 := alloc.vec.Vec.deref keep1
  canon.write_members members s2 out
partial_fixpoint

/-- [averin_decision_core::canon::write_members]: loop 1:
    Source: 'core/src/canon.rs', lines 292:4-306:5 -/
@[rust_loop]
def canon.write_members_loop1
  (members : alloc.vec.Vec (String × canon.CanonValue))
  (out : alloc.vec.Vec Std.U8) (keys : alloc.vec.Vec String)
  (units : alloc.vec.Vec (alloc.vec.Vec Std.U16))
  (src : alloc.vec.Vec Std.Usize) (order : alloc.vec.Vec Std.Usize)
  (unique : Bool) (n : Std.Usize) :
  Result ((alloc.vec.Vec Std.U8) × Bool)
  := do
  let i := alloc.vec.Vec.len order
  if n < i
  then
    let (out1, unique1) ←
      if n > 0#usize
      then
        do
        let out2 ← alloc.vec.Vec.push out 44#u8
        let i1 ← n - 1#usize
        let i2 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
            order i1
        let v ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            (alloc.vec.Vec Std.U16)) units i2
        let i3 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
            order n
        let v1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
            (alloc.vec.Vec Std.U16)) units i3
        let b ←
          alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqU16 v v1
        let b1 ← if b
                   then ok false
                   else ok unique
        ok (out2, b1)
      else ok (out, unique)
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize)
        order n
    let s ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice String) keys
        i1
    let s1 ← alloc.string.String.as_bytes s
    let out2 ← canon.escape_into s1 out1
    let out3 ← alloc.vec.Vec.push out2 58#u8
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.Usize) src
        i1
    let (_, cv) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (String ×
        canon.CanonValue)) members i2
    let (b, out4) ← canon.write_canonical cv out3
    let unique2 ← if b
                    then ok unique1
                    else ok false
    let n1 ← n + 1#usize
    canon.write_members_loop1 members out4 keys units src order unique2 n1
  else ok (out, unique)
partial_fixpoint

/-- [averin_decision_core::canon::write_members]:
    Source: 'core/src/canon.rs', lines 273:0-309:1 -/
def canon.write_members
  (members : alloc.vec.Vec (String × canon.CanonValue)) (keep : Slice Bool)
  (out : alloc.vec.Vec Std.U8) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  let (keys, units, src) ←
    canon.write_members_loop0 members keep (alloc.vec.Vec.new String)
      (alloc.vec.Vec.new (alloc.vec.Vec Std.U16)) (alloc.vec.Vec.new Std.Usize)
      0#usize
  let s := alloc.vec.Vec.deref units
  let i := alloc.vec.Vec.len units
  let v ← canon.positions i
  let s1 := alloc.vec.Vec.deref v
  let order ← canon.sort_by_units s s1
  let out1 ← alloc.vec.Vec.push out 123#u8
  let (out2, unique) ←
    canon.write_members_loop1 members out1 keys units src order true 0#usize
  let out3 ← alloc.vec.Vec.push out2 125#u8
  ok (unique, out3)
partial_fixpoint

end

/-- [averin_decision_core::checkpoint::CHECKPOINT_DOMAIN]
    Source: 'core/src/checkpoint.rs', lines 12:0-12:67
    Visibility: public -/
@[global_simps, irreducible]
def checkpoint.CHECKPOINT_DOMAIN : Str := toStr "flightrecorder.checkpoint.v2"

/-- [averin_decision_core::checkpoint::CHECKPOINT_CANON_VERSION]
    Source: 'core/src/checkpoint.rs', lines 13:0-13:51
    Visibility: public -/
@[global_simps, irreducible]
def checkpoint.CHECKPOINT_CANON_VERSION : Str := toStr "rcp-1"

/-- [averin_decision_core::hashx::ascii_string]:
    Source: 'core/src/hashx.rs', lines 42:0-47:1 -/
def hashx.ascii_string (bytes : alloc.vec.Vec Std.U8) : Result String := do
  let r ← alloc.string.String.from_utf8 bytes
  match r with
  | core.result.Result.Ok s => ok s
  | core.result.Result.Err _ => fail panic

/-- [averin_decision_core::hashx::HEX]
    Source: 'core/src/hashx.rs', lines 30:0-30:43 -/
@[global_simps, irreducible]
def hashx.HEX : Array Std.U8 16#usize :=
  Array.make 16#usize [
    48#u8, 49#u8, 50#u8, 51#u8, 52#u8, 53#u8, 54#u8, 55#u8, 56#u8, 57#u8,
    97#u8, 98#u8, 99#u8, 100#u8, 101#u8, 102#u8
    ]

/-- [averin_decision_core::hashx::hex_lower_into]: loop 0:
    Source: 'core/src/hashx.rs', lines 35:4-39:5 -/
@[rust_loop]
def hashx.hex_lower_into_loop
  (b : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i1 := Slice.len b
  if i < i1
  then
    let i2 ← Slice.index_usize b i
    let i3 ← i2 >>> 4#i32
    let i4 ← lift (UScalar.cast .Usize i3)
    let i5 ← Array.index_usize hashx.HEX i4
    let out1 ← alloc.vec.Vec.push out i5
    let i6 ← lift (i2 &&& 15#u8)
    let i7 ← lift (UScalar.cast .Usize i6)
    let i8 ← Array.index_usize hashx.HEX i7
    let out2 ← alloc.vec.Vec.push out1 i8
    let i9 ← i + 1#usize
    hashx.hex_lower_into_loop b out2 i9
  else ok out
partial_fixpoint

/-- [averin_decision_core::hashx::hex_lower_into]:
    Source: 'core/src/hashx.rs', lines 33:0-40:1 -/
@[reducible]
def hashx.hex_lower_into
  (b : Slice Std.U8) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  hashx.hex_lower_into_loop b out 0#usize

/-- [averin_decision_core::hashx::sha256_prefixed]:
    Source: 'core/src/hashx.rs', lines 56:0-61:1
    Visibility: public -/
def hashx.sha256_prefixed (data : Slice Std.U8) : Result String := do
  let s := alloc.vec.Vec.with_capacity Std.U8 71#usize
  let s1 ←
    lift (Array.to_slice
      (Array.make 7#usize [
        115#u8, 104#u8, 97#u8, 50#u8, 53#u8, 54#u8, 58#u8
        ]))
  let s2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 s s1
  let a ← hashx.sha256 data
  let s3 ← lift (Array.to_slice a)
  let s4 ← hashx.hex_lower_into s3 s2
  hashx.ascii_string s4

/-- [averin_decision_core::hashx::MAX_LP_LEN]
    Source: 'core/src/hashx.rs', lines 6:0-6:48
    Visibility: public -/
@[global_simps, irreducible]
def hashx.MAX_LP_LEN : Result Std.Usize :=
  ok (UScalar.cast .Usize core.num.U32.MAX)

/-- [averin_decision_core::hashx::lp_into]:
    Source: 'core/src/hashx.rs', lines 10:0-17:1
    Visibility: public -/
def hashx.lp_into
  (out : alloc.vec.Vec Std.U8) (b : Slice Std.U8) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  let i := Slice.len b
  let i1 ← hashx.MAX_LP_LEN
  if i > i1
  then ok (false, out)
  else
    let i2 := Slice.len b
    let i3 ← lift (UScalar.cast .U32 i2)
    let a ← lift (core.num.U32.to_be_bytes i3)
    let s ← lift (Array.to_slice a)
    let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
    let out2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 b
    ok (true, out2)

/-- [averin_decision_core::hashx::lp_str_into]:
    Source: 'core/src/hashx.rs', lines 20:0-22:1
    Visibility: public -/
def hashx.lp_str_into
  (out : alloc.vec.Vec Std.U8) (s : Str) :
  Result (Bool × (alloc.vec.Vec Std.U8))
  := do
  let s1 ← core.str.Str.as_bytes s
  hashx.lp_into out s1

/-- [averin_decision_core::record::body_preimage]:
    Source: 'core/src/record.rs', lines 209:0-232:1 -/
def record.body_preimage
  (value : canon.CanonValue) (strip : Slice Str) :
  Result (core.result.Result (alloc.vec.Vec Std.U8) record.PreimageFault)
  := do
  match value with
  | canon.CanonValue.Null =>
    ok (core.result.Result.Err record.PreimageFault.NotObject)
  | canon.CanonValue.Bool _ =>
    ok (core.result.Result.Err record.PreimageFault.NotObject)
  | canon.CanonValue.Int _ =>
    ok (core.result.Result.Err record.PreimageFault.NotObject)
  | canon.CanonValue.Str _ =>
    ok (core.result.Result.Err record.PreimageFault.NotObject)
  | canon.CanonValue.Array _ =>
    ok (core.result.Result.Err record.PreimageFault.NotObject)
  | canon.CanonValue.Object m =>
    let o ← canon.member value (toStr "domain")
    match o with
    | none => ok (core.result.Result.Err record.PreimageFault.MissingDomain)
    | some cv =>
      match cv with
      | canon.CanonValue.Null =>
        ok (core.result.Result.Err record.PreimageFault.DomainNotString)
      | canon.CanonValue.Bool _ =>
        ok (core.result.Result.Err record.PreimageFault.DomainNotString)
      | canon.CanonValue.Int _ =>
        ok (core.result.Result.Err record.PreimageFault.DomainNotString)
      | canon.CanonValue.Str s =>
        let o1 ← canon.member value (toStr "canon_version")
        match o1 with
        | none =>
          ok (core.result.Result.Err record.PreimageFault.MissingCanonVersion)
        | some cv1 =>
          match cv1 with
          | canon.CanonValue.Null =>
            ok (core.result.Result.Err
              record.PreimageFault.CanonVersionNotString)
          | canon.CanonValue.Bool _ =>
            ok (core.result.Result.Err
              record.PreimageFault.CanonVersionNotString)
          | canon.CanonValue.Int _ =>
            ok (core.result.Result.Err
              record.PreimageFault.CanonVersionNotString)
          | canon.CanonValue.Str s1 =>
            let s2 ← alloc.string.String.Insts.CoreOpsDerefDerefStr.deref s
            let (b, preimage) ←
              hashx.lp_str_into (alloc.vec.Vec.new Std.U8) s2
            if b
            then
              let s3 ←
                alloc.string.String.Insts.CoreOpsDerefDerefStr.deref s1
              let (b1, preimage1) ← hashx.lp_str_into preimage s3
              if b1
              then
                let (b2, preimage2) ← canon.write_object m strip preimage1
                if b2
                then ok (core.result.Result.Ok preimage2)
                else
                  ok (core.result.Result.Err record.PreimageFault.DuplicateKey)
              else ok (core.result.Result.Err record.PreimageFault.TooLong)
            else ok (core.result.Result.Err record.PreimageFault.TooLong)
          | canon.CanonValue.Array _ =>
            ok (core.result.Result.Err
              record.PreimageFault.CanonVersionNotString)
          | canon.CanonValue.Object _ =>
            ok (core.result.Result.Err
              record.PreimageFault.CanonVersionNotString)
      | canon.CanonValue.Array _ =>
        ok (core.result.Result.Err record.PreimageFault.DomainNotString)
      | canon.CanonValue.Object _ =>
        ok (core.result.Result.Err record.PreimageFault.DomainNotString)

/-- [averin_decision_core::checkpoint::checkpoint_preimage]:
    Source: 'core/src/checkpoint.rs', lines 135:0-137:1 -/
def checkpoint.checkpoint_preimage
  (cp : canon.CanonValue) :
  Result (core.result.Result (alloc.vec.Vec Std.U8) record.PreimageFault)
  := do
  let s ←
    lift (Array.to_slice
      (Array.make 3#usize [
        toStr "anchor", toStr "checkpoint_hash", toStr "sig"
        ]))
  record.body_preimage cp s

/-- [averin_decision_core::checkpoint::checkpoint_hash]:
    Source: 'core/src/checkpoint.rs', lines 122:0-124:1 -/
def checkpoint.checkpoint_hash
  (cp : canon.CanonValue) :
  Result (core.result.Result String record.PreimageFault)
  := do
  let r ← checkpoint.checkpoint_preimage cp
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let s := alloc.vec.Vec.deref val
    let s1 ← hashx.sha256_prefixed s
    ok (core.result.Result.Ok s1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      String (core.convert.FromSame record.PreimageFault) residual

/-- [averin_decision_core::record::RECORD_DOMAIN]
    Source: 'core/src/record.rs', lines 9:0-9:59
    Visibility: public -/
@[global_simps, irreducible]
def record.RECORD_DOMAIN : Str := toStr "flightrecorder.record.v2"

/-- [averin_decision_core::record::CANON_VERSION]
    Source: 'core/src/record.rs', lines 10:0-10:40
    Visibility: public -/
@[global_simps, irreducible] def record.CANON_VERSION : Str := toStr "rcp-1"

/-- [averin_decision_core::record::body_hash]:
    Source: 'core/src/record.rs', lines 195:0-197:1 -/
def record.body_hash
  (value : canon.CanonValue) (strip : Slice Str) :
  Result (core.result.Result String record.PreimageFault)
  := do
  let r ← record.body_preimage value strip
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let s := alloc.vec.Vec.deref val
    let s1 ← hashx.sha256_prefixed s
    ok (core.result.Result.Ok s1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      String (core.convert.FromSame record.PreimageFault) residual

/-- [averin_decision_core::record::record_preimage]:
    Source: 'core/src/record.rs', lines 256:0-258:1 -/
def record.record_preimage
  (body : canon.CanonValue) :
  Result (core.result.Result (alloc.vec.Vec Std.U8) record.PreimageFault)
  := do
  let s ←
    lift (Array.to_slice
      (Array.make 2#usize [ toStr "content_hash", toStr "sig" ]))
  record.body_preimage body s

/-- [averin_decision_core::record::record_hash]:
    Source: 'core/src/record.rs', lines 244:0-246:1 -/
def record.record_hash
  (body : canon.CanonValue) :
  Result (core.result.Result String record.PreimageFault)
  := do
  let r ← record.record_preimage body
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let s := alloc.vec.Vec.deref val
    let s1 ← hashx.sha256_prefixed s
    ok (core.result.Result.Ok s1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      String (core.convert.FromSame record.PreimageFault) residual

/-- [averin_decision_core::sign::RECORD_SIG_TAG]
    Source: 'core/src/sign.rs', lines 9:0-9:56
    Visibility: public -/
@[global_simps, irreducible]
def sign.RECORD_SIG_TAG : Str := toStr "averin.record.sig.v1"

/-- [averin_decision_core::sign::CHECKPOINT_SIG_TAG]
    Source: 'core/src/sign.rs', lines 10:0-10:64
    Visibility: public -/
@[global_simps, irreducible]
def sign.CHECKPOINT_SIG_TAG : Str := toStr "averin.checkpoint.sig.v1"

/-- [averin_decision_core::sign::preimage]:
    Source: 'core/src/sign.rs', lines 40:0-47:1
    Visibility: public -/
def sign.preimage
  (tag : Str) (content_hash : Str) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  let (b, pre) ← hashx.lp_str_into (alloc.vec.Vec.new Std.U8) tag
  if b
  then
    let s ← core.str.Str.as_bytes content_hash
    let pre1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 pre s
    ok (some pre1)
  else ok none

end averin_decision_core
