-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [averin_decision_core]: type definitions
import Aeneas
import Extracted.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace averin_decision_core

/-- [averin_decision_core::canon::CanonValue]
    Source: 'core/src/canon.rs', lines 17:0-28:1
    Visibility: public -/
@[discriminant isize]
inductive canon.CanonValue where
| Null : canon.CanonValue
| Bool : Bool → canon.CanonValue
| Int : Std.I64 → canon.CanonValue
| Str : String → canon.CanonValue
| Array : alloc.vec.Vec canon.CanonValue → canon.CanonValue
| Object : alloc.vec.Vec (String × canon.CanonValue) → canon.CanonValue

/-- [averin_decision_core::record::PreimageFault]
    Source: 'core/src/record.rs', lines 162:0-170:1 -/
@[discriminant isize]
inductive record.PreimageFault where
| NotObject : record.PreimageFault
| MissingDomain : record.PreimageFault
| DomainNotString : record.PreimageFault
| MissingCanonVersion : record.PreimageFault
| CanonVersionNotString : record.PreimageFault
| TooLong : record.PreimageFault
| DuplicateKey : record.PreimageFault

end averin_decision_core
