//! vectors/params-commitment.v1.json is OWNED by averin (generated by the independent Python
//! reference scripts/vectors/gen_params_commitment.py) and copied byte for byte into vultrino,
//! which computes the same commitment for its use PoP. This test checks the shipped
//! `commit::commit` reproduces every vector, and refuses every nonce the file lists as rejected
//! once decoded the way the FFI decodes them (64 lowercase hex characters only).

use averin_decision_core::canon::CanonValue;
use averin_decision_core::commit::{commit, FieldDomain};
use std::path::PathBuf;

fn vectors() -> CanonValue {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("vectors")
        .join("params-commitment.v1.json");
    let text = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {p:?}: {e}"));
    CanonValue::parse(&text).unwrap_or_else(|e| panic!("parse {p:?}: {e}"))
}

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "even hex");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn commit_reproduces_every_pinned_commitment() {
    let v = vectors();
    let cases = v.get("vectors").and_then(|c| c.as_array()).expect("vectors");
    assert!(cases.len() >= 11, "vector file too small: {}", cases.len());
    let mut domains = std::collections::BTreeSet::new();
    for c in cases {
        let s = |k: &str| c.get(k).and_then(|x| x.as_str()).unwrap().to_string();
        let id = s("id");
        let domain = FieldDomain::parse(&s("domain")).unwrap_or_else(|| panic!("{id}: domain"));
        domains.insert(s("domain"));
        let got = commit(domain, &unhex(&s("value_hex")), &unhex(&s("nonce_hex")))
            .unwrap_or_else(|e| panic!("{id}: {e}"));
        assert_eq!(got, s("expect"), "{id}");
    }
    assert_eq!(domains.len(), 4, "every field domain is exercised: {domains:?}");
}

#[test]
fn a_nonce_that_is_not_32_bytes_is_refused() {
    let v = vectors();
    let rejects = v
        .get("reject_nonce_hex")
        .and_then(|c| c.as_array())
        .expect("reject_nonce_hex");
    assert!(rejects.len() >= 8);
    for r in rejects {
        let id = r.get("id").and_then(|x| x.as_str()).unwrap();
        let hex = r.get("nonce_hex").and_then(|x| x.as_str()).unwrap();
        // Strict decode: exactly 64 lowercase hex characters, as the FFI requires.
        let strict = hex.len() == 64
            && hex
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b));
        assert!(!strict, "{id}: listed as rejected but is a valid nonce");
        let decoded = if hex.len() % 2 == 0 && hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            unhex(hex)
        } else {
            Vec::new()
        };
        if decoded.len() != 32 {
            assert!(commit(FieldDomain::Input, b"x", &decoded).is_err(), "{id}");
        }
    }
}
